### ISSUE TITLE
Cannot resolve dependency css-loader

### ISSUE THREAD

**Issue by looterz** [rikmms/progress-bar-4-axios#1]
Here is the error message I receive when attempting to use this module as described in the README.

```
×  node_modules\axios-progress-bar\dist\index.js:173:28: Cannot resolve dependency '!!../css-loader/ind  171 | nprogresif(!content.locals) {
  172 |                 module.hot.accept("!!../css-loader/index.js!./nprogress.css", function() {
> 173 |                         var newContent = require("!!../css-loader/index.js!./nprogress.css");
      |                                                  ^
  174 |                         if(typeof newContent === 'string') newContent = [[module.id, newContent, '']];
  175 |                         update(newContent);
  176 |                 });
```

**Comment by rikmms** [comment]
Hi, @looterz.

I updated the module to use the split CSS functionality in Webpack (check the updated documentation in the README file). With that, the CSS file that contains the customization of the progress bar is now imported separately from the JS bundle (it's typically best practice to split the CSS out into a separate file).
