### ISSUE TITLE
NProgress.config() doesn't seem to configure properly

### ISSUE THREAD

**Issue by jndietz** [rikmms/progress-bar-4-axios#12]
Everything seems fairly straightforward... Here is how I am instantiating the progress bar in my `index.js`...

```js
import { loadProgressBar } from 'axios-progress-bar'
const progressBarConfig = NProgress.configure({ parent: '#axios-progress-bar', showSpinner: false });
loadProgressBar(progressBarConfig);
```

I would have expected to see the progress bar attached to the top of my `<div id="axios-progress-bar></div>` element, and the spinner is hidden.  Is this not the right usage?  The spinner still shows and the progress bar is still stuck to the very top of the page.

I've also tried...

```js
import { loadProgressBar } from 'axios-progress-bar'
const progressBarConfig = { parent: '#axios-progress-bar', showSpinner: false };
loadProgressBar(progressBarConfig);
```

**Comment by D-i-l-r-u-k-s-h-i** [comment]
`const progressBarConfig = { showSpinner: false };` works for me
