### ISSUE TITLE
Doesn't work with axios custom instance

### ISSUE THREAD

**Issue by wuelcas** [rikmms/progress-bar-4-axios#5]
I made an [axios custom instance](https://github.com/axios/axios#custom-instance-defaults) and the progress bar doesn't disappear when the request ends. Looking at the source code, you are not handling custom instance, just the normal `axios` instance.

**Comment by wuelcas** [comment]
Never mind about the `config` thing, I see that's the config for the nprogress package, you should add that to the README

**Comment by rikmms** [comment]
New version [1.2.0] published on NPM with this new feature.

**Comment by piyyushhpatel** [comment]
I am getting error in a react typescript project 
my packages are
"axios": "^0.19.0",
"axios-progress-bar": "^1.2.0",

ERROR in /Users/jasmine/jas/work/node_modules/axios-progress-bar/dist/index.js
Module not found: Error: Can't resolve 'axios' in '/Users/jasmine/jas/work/node_modules/axios-progress-bar/dist'
